### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/ShanghaiDensities256/densities_test_A.npy'

### ISSUE THREAD

**Issue by Tikam02** [prateekmalhotra/crowd-counting-GAN#1]
@prateekmalhotra
  where is this file or directory.

**Comment by prateekm08** [comment]
This is part of the ShanghaiTech dataset. Unfortunately, I am not allowed to distribute the dataset and the code used to generate density maps. However, you can contact the authors of the paper and they will be happy to help you out.

**Comment by Tikam02** [comment]
Thanks That will help.

**Comment by ghost** [comment]
Did you get the document('/ShanghaiDensities256/densities_test_A.npy')? I have already sent a email to the  author of MCNN, but no response until now.
